/* console_themes.h -- GENERATED by tools/reduce_themes.c.  Do not edit.
 *
 * The core's built-in themes, reduced to the sixteen colours each machine
 * has.  They are the same definitions the Windows build shows by name and
 * the same reduction it would apply on a sixteen-colour display; what the
 * targets that include this file give up is the registry that would let them
 * hold three hundred more, not the meaning of a theme.
 *
 * To change one, or to add one, edit note_builtin_themes in
 * src/core/note_theme.c and re-run tools/reduce_themes.ps1.
 *
 * Field order is console_theme's, declared in console_main.c:
 *     name, bg, tok[TOK_COUNT], gutter_fg, gutter_bg, ui_fg, ui_bg, caret
 */

#if defined(__CC65__)
/* The machine's own screen: the one theme a C64 user was never told about. */
#define THEME_DEFAULT 2

/* Reduced onto the VIC-II's sixteen, in the C64's order. */
static const console_theme kThemes[] = {
    { "Light",  1,
      { 11,  6,  5, 12,  9,  8, 14, 11 },
      15,  1, 11,  1, 11 },
    { "Dark",  0,
      {  1, 14,  3,  5,  7, 13, 10,  1 },
      12,  0,  1, 11,  1 },
    { "Commodore 64",  6,
      { 14,  1,  3, 12, 13,  7, 10, 15 },
      12,  6,  6, 14, 14 }
};

#else
/* A PC text screen is black when DOS hands it over. */
#define THEME_DEFAULT 1

/* Reduced onto CGA/EGA/VGA's sixteen. */
static const console_theme kThemes[] = {
    { "Light", 15,
      {  0,  1,  3,  8,  2,  4,  5,  0 },
       8, 15,  0, 15,  0 },
    { "Dark",  0,
      {  7,  3, 11,  8,  6, 15, 13,  7 },
       8,  0,  7,  0,  7 },
    { "Commodore 64",  1,
      {  8, 15,  3,  2, 11, 14,  6,  7 },
       8,  1,  1,  8,  8 }
};
#endif
