"""font_to_c.py - turns a bitmap font into a C table the DOS build can upload.

    python tools/font_to_c.py ter-u16n.bdf  src/platform/console/font_terminus.h \
        --name kFontTerminus --note "Terminus 4.49.1, SIL OFL 1.1"
    python tools/font_to_c.py VGA8.F16 src/platform/console/font_vga.h \
        --name kFontVGA

Two input formats, because the two fonts worth having arrive differently:

  .bdf   text, one glyph per STARTCHAR block, indexed by Unicode codepoint
  .f16   raw, exactly 256 glyphs of 16 bytes, already in the VGA's own order

The output is always the raw form: 256 glyphs of 16 bytes, one byte per
scanline, high bit leftmost -- what INT 10h/AX=1110h wants and what the VGA
character generator holds.  A BDF is therefore reordered on the way through,
from Unicode into code page 437, which is the order every DOS text mode reads
its glyphs in.  Python knows that mapping already, so the table is not one we
have to carry or get wrong.
"""

import argparse
import os
import sys

CELL_W = 8
CELL_H = 16
GLYPHS = 256


def read_raw(path):
    """A .f16 is already the target format; the only question is its size."""
    with open(path, 'rb') as f:
        data = f.read()
    want = GLYPHS * CELL_H
    if len(data) != want:
        raise SystemExit('%s is %d bytes, expected %d (256 glyphs of %d rows)'
                         % (path, len(data), want, CELL_H))
    return [list(data[i * CELL_H:(i + 1) * CELL_H]) for i in range(GLYPHS)]


def read_bdf(path):
    """Returns {codepoint: [16 bytes]}.

    A BDF glyph is placed by its own bounding box relative to the baseline,
    not by the cell, so each one has to be lifted back into the cell before it
    means anything to the VGA.  Rows are padded to whole bytes in the file; at
    8 pixels wide that is one byte, but the padding is honoured anyway so a
    wider face does not silently shear.
    """
    glyphs = {}
    fbb = None
    enc = None
    bbx = None
    rows = None

    with open(path, 'r', encoding='latin-1') as f:
        for line in f:
            parts = line.split()
            if not parts:
                continue
            key = parts[0]

            if key == 'FONTBOUNDINGBOX':
                fbb = [int(v) for v in parts[1:5]]
            elif key == 'ENCODING':
                enc = int(parts[1])
            elif key == 'BBX':
                bbx = [int(v) for v in parts[1:5]]
            elif key == 'BITMAP':
                rows = []
            elif key == 'ENDCHAR':
                if enc is not None and enc >= 0 and bbx and rows is not None:
                    glyphs[enc] = place(rows, bbx, fbb)
                enc, bbx, rows = None, None, None
            elif rows is not None:
                rows.append(parts[0])

    if not glyphs:
        raise SystemExit('%s contained no glyphs' % path)
    return glyphs


def place(rows, bbx, fbb):
    """Lifts one glyph's rows into a CELL_W x CELL_H cell."""
    bw, bh, bx, by = bbx
    fh, fy = (fbb[1], fbb[3]) if fbb else (CELL_H, 0)

    # The cell's top, counted down from the font's ascent, is where this
    # glyph's own box begins.
    top = (fh + fy) - (bh + by)
    stride = (bw + 7) // 8

    cell = [0] * CELL_H
    for i, hexrow in enumerate(rows[:bh]):
        y = top + i
        if not 0 <= y < CELL_H:
            continue
        try:
            value = int(hexrow, 16)
        except ValueError:
            continue
        # Left-align the row, then shift it to the glyph's x offset.
        row = (value >> ((stride - 1) * 8)) & 0xFF if stride else 0
        if bx > 0:
            row >>= bx
        elif bx < 0:
            row = (row << -bx) & 0xFF
        cell[y] = row
    return cell


def to_cp437(glyphs):
    """Reindexes a Unicode-keyed font into the VGA's code page 437 order."""
    out = []
    missing = []
    for i in range(GLYPHS):
        cp = ord(bytes([i]).decode('cp437'))
        if cp in glyphs:
            out.append(glyphs[cp])
        else:
            out.append([0] * CELL_H)
            missing.append(i)
    return out, missing


def emit(cells, name, note, source):
    lines = []
    lines.append('/* Generated by tools/font_to_c.py from %s -- do not edit.'
                 % os.path.basename(source))
    if note:
        lines.append(' *')
        lines.append(' * %s' % note)
    lines.append(' *')
    lines.append(' * 256 glyphs of %d scanlines, one byte per row, high bit'
                 % CELL_H)
    lines.append(' * leftmost, in code page 437 order. */')
    lines.append('')
    lines.append('static const unsigned char %s[256][%d] = {' % (name, CELL_H))
    for i, cell in enumerate(cells):
        body = ','.join('0x%02X' % b for b in cell)
        lines.append('  {%s},   /* %3d */' % (body, i))
    lines.append('};')
    lines.append('')
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('input')
    ap.add_argument('output')
    ap.add_argument('--name', default='kFont')
    ap.add_argument('--note', default='')
    args = ap.parse_args()

    ext = os.path.splitext(args.input)[1].lower()
    if ext == '.bdf':
        cells, missing = to_cp437(read_bdf(args.input))
        if missing:
            print('%d of 256 positions have no glyph and are blank: %s'
                  % (len(missing), ' '.join(str(m) for m in missing[:16])
                     + (' ...' if len(missing) > 16 else '')))
    else:
        cells = read_raw(args.input)
        missing = []

    blank = sum(1 for c in cells if not any(c))
    print('%d glyphs, %d blank' % (len(cells), blank))

    with open(args.output, 'w', newline='\n') as f:
        f.write(emit(cells, args.name, args.note, args.input))
    print('wrote %s (%d bytes of table)' % (args.output, GLYPHS * CELL_H))


if __name__ == '__main__':
    main()
