"""make_gbfont.py - the 4x8 font note/gb packs two characters per tile with.

    python tools/make_gbfont.py src/platform/gb/gb_font.h

The glyphs are 3x5 inside a 4x8 cell: three pixels of ink, one of spacing, one
blank row above and two below.  Three pixels is the narrowest a Latin alphabet
stays distinguishable at -- at two, E, F and B are the same shape.

The source form is the picture, not the hex, because a font is the one kind of
table where a human can see a mistake instantly and cannot see it at all once
it has been turned into bytes.  ASCII 32..95 only: lowercase is folded to
uppercase by the caller, which costs nothing and saves half the table on a
machine where the table lives in ROM beside an interpreter.

Output is one byte per pixel row, ink in the high nibble, so that composing a
tile from a left and a right character is:

    tile[i] = (left[i] & 0xF0) | (right[i] >> 4)
"""

import sys

# 3 wide, 5 tall, top to bottom.
GLYPHS = {
    ' ': "..." "..." "..." "..." "...",
    '!': ".#." ".#." ".#." "..." ".#.",
    '"': "#.#" "#.#" "..." "..." "...",
    '#': "#.#" "###" "#.#" "###" "#.#",
    '$': ".##" "##." ".#." ".##" "##.",
    '%': "#.#" "..#" ".#." "#.." "#.#",
    '&': ".#." "#.#" ".#." "#.#" ".##",
    "'": ".#." ".#." "..." "..." "...",
    '(': "..#" ".#." ".#." ".#." "..#",
    ')': "#.." ".#." ".#." ".#." "#..",
    '*': "..." "#.#" ".#." "#.#" "...",
    '+': "..." ".#." "###" ".#." "...",
    ',': "..." "..." "..." ".#." "#..",
    '-': "..." "..." "###" "..." "...",
    '.': "..." "..." "..." "..." ".#.",
    '/': "..#" "..#" ".#." "#.." "#..",

    '0': "###" "#.#" "#.#" "#.#" "###",
    '1': ".#." "##." ".#." ".#." "###",
    '2': "##." "..#" ".#." "#.." "###",
    '3': "###" "..#" ".##" "..#" "###",
    '4': "#.#" "#.#" "###" "..#" "..#",
    '5': "###" "#.." "###" "..#" "###",
    '6': ".##" "#.." "###" "#.#" "###",
    '7': "###" "..#" ".#." ".#." ".#.",
    '8': "###" "#.#" "###" "#.#" "###",
    '9': "###" "#.#" "###" "..#" "##.",

    ':': "..." ".#." "..." ".#." "...",
    ';': "..." ".#." "..." ".#." "#..",
    '<': "..#" ".#." "#.." ".#." "..#",
    '=': "..." "###" "..." "###" "...",
    '>': "#.." ".#." "..#" ".#." "#..",
    '?': "##." "..#" ".#." "..." ".#.",
    '@': ".#." "#.#" "###" "#.." ".##",

    'A': ".#." "#.#" "###" "#.#" "#.#",
    'B': "##." "#.#" "##." "#.#" "##.",
    'C': ".##" "#.." "#.." "#.." ".##",
    'D': "##." "#.#" "#.#" "#.#" "##.",
    'E': "###" "#.." "##." "#.." "###",
    'F': "###" "#.." "##." "#.." "#..",
    'G': ".##" "#.." "#.#" "#.#" ".##",
    'H': "#.#" "#.#" "###" "#.#" "#.#",
    'I': "###" ".#." ".#." ".#." "###",
    'J': "..#" "..#" "..#" "#.#" ".#.",
    'K': "#.#" "##." "#.." "##." "#.#",
    'L': "#.." "#.." "#.." "#.." "###",
    'M': "#.#" "###" "###" "#.#" "#.#",
    'N': "#.#" "###" "###" "###" "#.#",
    'O': ".#." "#.#" "#.#" "#.#" ".#.",
    'P': "##." "#.#" "##." "#.." "#..",
    'Q': ".#." "#.#" "#.#" "##." ".##",
    'R': "##." "#.#" "##." "#.#" "#.#",
    'S': ".##" "#.." ".#." "..#" "##.",
    'T': "###" ".#." ".#." ".#." ".#.",
    'U': "#.#" "#.#" "#.#" "#.#" "###",
    'V': "#.#" "#.#" "#.#" "#.#" ".#.",
    'W': "#.#" "#.#" "###" "###" "#.#",
    'X': "#.#" "#.#" ".#." "#.#" "#.#",
    'Y': "#.#" "#.#" ".#." ".#." ".#.",
    'Z': "###" "..#" ".#." "#.." "###",

    '[': ".##" ".#." ".#." ".#." ".##",
    '\\': "#.." "#.." ".#." "..#" "..#",
    ']': "##." ".#." ".#." ".#." "##.",
    '^': ".#." "#.#" "..." "..." "...",
    '_': "..." "..." "..." "..." "###",
}

FIRST, LAST = 32, 95      # ' ' .. '_'
CELL_H = 8
TOP = 1                   # blank rows above the glyph


def rows_of(art):
    """The five 3-character rows of one glyph's picture."""
    if len(art) != 15:
        raise SystemExit("a glyph is 5 rows of 3, got %d cells" % len(art))
    return [art[i * 3:(i + 1) * 3] for i in range(5)]


def glyph_bytes(art):
    """Eight bytes, ink in the high nibble."""
    out = [0] * CELL_H
    for i, row in enumerate(rows_of(art)):
        bits = 0
        for x, c in enumerate(row):
            if c == '#':
                bits |= 0x80 >> x
        out[TOP + i] = bits
    return out


def main():
    dest = sys.argv[1] if len(sys.argv) > 1 else 'src/platform/gb/gb_font.h'

    missing = [chr(c) for c in range(FIRST, LAST + 1) if chr(c) not in GLYPHS]
    if missing:
        raise SystemExit('no glyph for: ' + ' '.join(missing))

    lines = []
    lines.append('/* Generated by tools/make_gbfont.py -- do not edit.')
    lines.append(' *')
    lines.append(' * 3x5 glyphs in a 4x8 cell, ASCII %d..%d, ink in the high'
                 % (FIRST, LAST))
    lines.append(' * nibble.  See the generator for why the source is a picture. */')
    lines.append('')
    lines.append('#ifndef GB_FONT_H')
    lines.append('#define GB_FONT_H')
    lines.append('')
    lines.append('#define FONT_FIRST %d' % FIRST)
    lines.append('#define FONT_LAST  %d' % LAST)
    lines.append('')
    lines.append('const unsigned char gb_font[%d][%d] = {'
                 % (LAST - FIRST + 1, CELL_H))

    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        body = ','.join('0x%02X' % b for b in glyph_bytes(GLYPHS[ch]))
        shown = ch if ch not in ('\\',) else '\\\\'
        lines.append('    {%s},   /* %s */' % (body, shown))

    lines.append('};')
    lines.append('')
    lines.append('#endif /* GB_FONT_H */')

    with open(dest, 'w', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')

    print('%d glyphs -> %s (%d bytes of table)'
          % (LAST - FIRST + 1, dest, (LAST - FIRST + 1) * CELL_H))


if __name__ == '__main__':
    main()
