/* reduce_themes.c — the console backends' theme tables, generated.
 *
 * A theme is one thing everywhere in note: a note_theme of RGB triples,
 * written in the note_conf format, mapped onto whatever the display can
 * actually show by note_theme_reduce().  Two of the console targets cannot
 * carry that machinery -- a 6502 with eight kilobytes of document, and a
 * real-mode PC with about a kilobyte of DGROUP spare -- so they get the same
 * themes reduced by the same code, only earlier: here, on a machine that has
 * room, with the answer written out as C.
 *
 * That is the whole point of this file.  What the small targets give up is how
 * MANY themes they carry, never what a theme IS; the alternative was a second
 * palette format maintained by hand beside the first, which is what used to be
 * in console_main.c and what this replaces.
 *
 * It includes the core's own sources rather than reimplementing anything.  A
 * generator that ported note_theme_reduce into Python would be a second
 * implementation of the thing being unified, and would drift.
 *
 *   cl /nologo /W3 tools\reduce_themes.c /Fe:build\reduce_themes.exe
 *   build\reduce_themes.exe > src\platform\console\console_themes.h
 *
 * tools\reduce_themes.ps1 does both and is the way to run it.  The output is
 * committed, so building for the C64 or for real-mode DOS needs neither this
 * tool nor a host compiler -- the same arrangement tools\font_to_c.py and
 * tools\import_packs.py already use.
 */

#include <stdio.h>

/* The core is written against nchar, which is UTF-16 on Windows by default.
 * The console backends are byte builds and their theme names are bytes, so
 * this tool is one too. */
#define NOTE_NCHAR_UTF16 0

#include "../src/core/note_theme.h"
#include "../src/core/note_reduce.h"

/* The three helpers the core asks the backend for.  A generator is a backend
 * of a sort: it is what note_theme.c is being linked against here. */
int n_len(const nchar *s)
{
    int i = 0;
    if (!s) return 0;
    while (s[i]) i++;
    return i;
}

int n_eq(const nchar *a, const nchar *b)
{
    while (*a && *a == *b) { a++; b++; }
    return *a == *b;
}

const nchar *note_basename(const nchar *path)
{
    const nchar *p = path, *last = path;
    for (; *p; p++)
        if (*p == '\\' || *p == '/') last = p + 1;
    return last;
}

/* note_theme.c widens its built-in definitions from char to nchar through
 * this, which for a byte build is the identity.  Defined here rather than by
 * including note_syntax.c, which would bring the whole lexer with it. */
const nchar *note_syntax_widen(const char *s) { return (const nchar *)s; }

#include "../src/core/note_conf.c"
#include "../src/core/note_theme.c"
#include "../src/core/note_reduce.c"

static note_arena g_arena;

/* One row of console_theme, in the field order console_main.c declares.  The
 * two have to agree and nothing can check that they do, so the order is
 * repeated in the generated file's header comment as well as here. */
static void emit_row(const note_theme *t, const note_color *pal)
{
    note_theme_map m;
    int k;

    note_theme_reduce(&m, t, pal, 16);

    printf("    { \"%s\", %2u,\n      { ", t->name, m.bg);
    for (k = 0; k < TOK_COUNT; k++)
        printf("%2u%s", m.tok[k], k + 1 < TOK_COUNT ? ", " : "");
    printf(" },\n      %2u, %2u, %2u, %2u, %2u }",
           m.gutter_fg, m.gutter_bg, m.ui_fg, m.ui_bg, m.caret);
}

/* Which row a machine starts on, by name rather than by number, so that
 * adding a theme to the core cannot silently change what a C64 boots into. */
static void emit_default(const char *name, const char *why)
{
    int i = note_theme_find(name);
    printf("/* %s */\n#define THEME_DEFAULT %d\n\n", why, i < 0 ? 0 : i);
}

static void emit_table(const char *what, const note_color *pal)
{
    int i, n = note_theme_count();

    printf("/* Reduced onto %s. */\n", what);
    printf("static const console_theme kThemes[] = {\n");
    for (i = 0; i < n; i++) {
        emit_row(note_theme_get(i), pal);
        printf(i + 1 < n ? ",\n" : "\n");
    }
    printf("};\n");
}

int main(void)
{
    /* The core's own built-ins and nothing else.  A target that can hold more
     * than three themes is a target that can hold the registry, and reads the
     * catalogue at run time instead of coming here. */
    note_theme_init(&g_arena);

    printf(
"/* console_themes.h -- GENERATED by tools/reduce_themes.c.  Do not edit.\n"
" *\n"
" * The core's built-in themes, reduced to the sixteen colours each machine\n"
" * has.  They are the same definitions the Windows build shows by name and\n"
" * the same reduction it would apply on a sixteen-colour display; what the\n"
" * targets that include this file give up is the registry that would let them\n"
" * hold three hundred more, not the meaning of a theme.\n"
" *\n"
" * To change one, or to add one, edit note_builtin_themes in\n"
" * src/core/note_theme.c and re-run tools/reduce_themes.ps1.\n"
" *\n"
" * Field order is console_theme's, declared in console_main.c:\n"
" *     name, bg, tok[TOK_COUNT], gutter_fg, gutter_bg, ui_fg, ui_bg, caret\n"
" */\n\n");

    printf("#if defined(__CC65__)\n");
    emit_default("Commodore 64",
                 "The machine's own screen: the one theme a C64 user was never"
                 " told about.");
    emit_table("the VIC-II's sixteen, in the C64's order", note_pal_c64);
    printf("\n#else\n");
    emit_default("Dark", "A PC text screen is black when DOS hands it over.");
    emit_table("CGA/EGA/VGA's sixteen", note_pal_ega16);
    printf("#endif\n");
    return 0;
}
